#!/usr/bin/env node
/**
 * Generates scripts/d1-seed.sql from the flag SVGs in ./flag-assets.
 *
 * Then load it into D1 (from the repo root or worker/):
 *   npx wrangler d1 execute FLAGS_DB --file=scripts/d1-seed.sql --remote
 *
 * Flags are SVG (plain text), so they are stored in a TEXT column.
 */
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const ASSETS = path.join(ROOT, "flag-assets");

function sqlString(s) {
  // Escape single quotes and strip control characters SQLite dislikes.
  return "'" + s.replace(/'/g, "''").replace(/[\x00]/g, "") + "'";
}

const files = fs
  .readdirSync(ASSETS)
  .filter((f) => /^[a-z]{2}\.svg$/.test(f))
  .sort();

if (!files.length) {
  console.error("No flag SVGs in flag-assets/. Run scripts/download-flags.sh first.");
  process.exit(1);
}

// D1 caps SQL statements at 100KB. Some flag SVGs (Serbia's coat of arms!)
// exceed that on their own, so oversized rows are inserted empty and then
// assembled with UPDATE || appends, each statement staying small.
const MAX_STMT_BYTES = 90 * 1024;
const APPEND_CHUNK = 55 * 1024; // raw content bytes per UPDATE statement

function statementsFor(code, svg) {
  const sizeBytes = Buffer.byteLength(svg);
  const prefix =
    `INSERT OR REPLACE INTO flags (country_code, content_type, content, size_bytes) VALUES ` +
    `(${sqlString(code)}, 'image/svg+xml', `;
  // Fast path: the whole statement fits in one go.
  if (prefix.length + svg.length + 40 < MAX_STMT_BYTES) {
    return [`${prefix}${sqlString(svg)}, ${sizeBytes});`];
  }
  const stmts = [`${prefix}'', ${sizeBytes});`];
  for (let i = 0; i < svg.length; i += APPEND_CHUNK) {
    stmts.push(
      `UPDATE flags SET content = content || ${sqlString(svg.slice(i, i + APPEND_CHUNK))} WHERE country_code = ${sqlString(code)};`
    );
  }
  return stmts;
}

const OUT_DIR = path.join(__dirname, "d1-seed");
fs.rmSync(OUT_DIR, { recursive: true, force: true });
fs.mkdirSync(OUT_DIR, { recursive: true });

const header = "-- Generated by scripts/make-d1-seed.js — do not edit by hand.\n";
let chunk = [header];
let chunkBytes = header.length;
let chunkIndex = 1;

function flush() {
  if (chunk.length === 1) return; // only the header — nothing to write
  const name = `${String(chunkIndex).padStart(2, "0")}.sql`;
  fs.writeFileSync(path.join(OUT_DIR, name), chunk.join("\n") + "\n");
  chunkIndex++;
  chunk = [header];
  chunkBytes = header.length;
}

let chunkBytesBudget = 80 * 1024; // per-file total, comfortably below the batch limit

for (const file of files) {
  const svg = fs.readFileSync(path.join(ASSETS, file), "utf8");
  const code = file.replace(".svg", "").toUpperCase();
  for (const stmt of statementsFor(code, svg)) {
    if (chunkBytes + stmt.length + 1 > chunkBytesBudget) flush();
    chunk.push(stmt);
    chunkBytes += stmt.length + 1;
  }
}
flush();

console.log(`==> wrote ${chunkIndex - 1} chunk files to ${OUT_DIR} (${files.length} flags, ≤80KB each)`);
console.log(`==> load them with:`);
console.log(`    bash scripts/load-d1.sh          # remote (production)`);
console.log(`    bash scripts/load-d1.sh --local  # local dev`);
